// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bill.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	BillId               int32    `protobuf:"varint,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	PledgeId             int32    `protobuf:"varint,2,opt,name=pledge_id,json=pledgeId,proto3" json:"pledge_id,omitempty"`
	UserId               int32    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CampaignId           int32    `protobuf:"varint,4,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	AmountCents          int32    `protobuf:"varint,5,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_24141385411f973b, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetBillId() int32 {
	if m != nil {
		return m.BillId
	}
	return 0
}

func (m *CreateRequest) GetPledgeId() int32 {
	if m != nil {
		return m.PledgeId
	}
	return 0
}

func (m *CreateRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateRequest) GetCampaignId() int32 {
	if m != nil {
		return m.CampaignId
	}
	return 0
}

func (m *CreateRequest) GetAmountCents() int32 {
	if m != nil {
		return m.AmountCents
	}
	return 0
}

func (m *CreateRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CreateResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_24141385411f973b, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "pb.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "pb.CreateResponse")
}

func init() { proto.RegisterFile("bill.proto", fileDescriptor_24141385411f973b) }

var fileDescriptor_24141385411f973b = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x49, 0xa0, 0x86, 0x4e, 0x4b, 0x25, 0x66, 0x01, 0x11, 0x2c, 0x08, 0x59, 0x75, 0x15,
	0x09, 0x38, 0x01, 0xea, 0x2a, 0xdb, 0x70, 0x80, 0xca, 0x8e, 0x47, 0x95, 0xa5, 0xd4, 0x36, 0xb1,
	0x7d, 0x39, 0x4e, 0x87, 0x26, 0xa6, 0x88, 0x2e, 0xff, 0x7b, 0xf3, 0xad, 0xf1, 0x00, 0x28, 0x33,
	0x8e, 0xad, 0x9f, 0x5c, 0x74, 0x58, 0x7a, 0xd5, 0x7c, 0x17, 0x70, 0xbb, 0x9b, 0x48, 0x46, 0xea,
	0xe9, 0x2b, 0x51, 0x88, 0xf8, 0x00, 0xd7, 0x3c, 0xb3, 0x37, 0xba, 0x2a, 0xea, 0x62, 0xbb, 0xe8,
	0x05, 0xc7, 0x4e, 0xe3, 0x13, 0x2c, 0xfd, 0x48, 0xfa, 0x40, 0xac, 0xca, 0x59, 0xdd, 0x64, 0xd0,
	0x69, 0x6e, 0xa5, 0x40, 0x13, 0xab, 0xcb, 0xdc, 0xe2, 0xd8, 0x69, 0x7c, 0x86, 0xd5, 0x20, 0x8f,
	0x5e, 0x9a, 0x83, 0x65, 0x79, 0x35, 0x4b, 0x38, 0xa1, 0x4e, 0xe3, 0x0b, 0xac, 0xe5, 0xd1, 0x25,
	0x1b, 0xf7, 0x03, 0xd9, 0x18, 0xaa, 0xc5, 0x3c, 0xb1, 0xca, 0x6c, 0xc7, 0x08, 0xef, 0x41, 0x84,
	0x28, 0x63, 0x0a, 0x95, 0xa8, 0x8b, 0xed, 0xb2, 0xff, 0x4d, 0x4d, 0x0d, 0x9b, 0xd3, 0xee, 0xc1,
	0x3b, 0x1b, 0x08, 0x37, 0x50, 0xfe, 0xed, 0x5d, 0x1a, 0xfd, 0xf6, 0x01, 0xeb, 0xcf, 0xa4, 0xc2,
	0x30, 0x19, 0x1f, 0x8d, 0xb3, 0xf8, 0x0a, 0x22, 0x37, 0xf0, 0xae, 0xf5, 0xaa, 0x3d, 0xfb, 0xf9,
	0x23, 0xfe, 0x47, 0xf9, 0xc1, 0xe6, 0x42, 0x89, 0xf9, 0x58, 0xef, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x35, 0x7d, 0x78, 0x82, 0x3a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SubscriptionClient is the client API for Subscription service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubscriptionClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type subscriptionClient struct {
	cc *grpc.ClientConn
}

func NewSubscriptionClient(cc *grpc.ClientConn) SubscriptionClient {
	return &subscriptionClient{cc}
}

func (c *subscriptionClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.Subscription/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionServer is the server API for Subscription service.
type SubscriptionServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

// UnimplementedSubscriptionServer can be embedded to have forward compatible implementations.
type UnimplementedSubscriptionServer struct {
}

func (*UnimplementedSubscriptionServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterSubscriptionServer(s *grpc.Server, srv SubscriptionServer) {
	s.RegisterService(&_Subscription_serviceDesc, srv)
}

func _Subscription_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Subscription/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Subscription_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Subscription",
	HandlerType: (*SubscriptionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Subscription_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bill.proto",
}
